### ISSUE TITLE
Support short YAML

### ISSUE THREAD

**Issue by avish9** [puresec/aws-parsecf#3]

**Comment by tomislacker** [comment]
Example:

```yaml
Conditions:
  HasDumpSchedule: !And
    - Condition: HasLoadSourceEnvironmentSlug
    - !Not [ !Equals [!Ref LoadScheduleExpression, ''] ]
```

```python
ConstructorError: could not determine a constructor for the tag '!And'
  in "/home/me/Projects/myproject/template.yml", line 295, column 20
```
